[build-system]
requires = ["scikit-build-core", "numpy"]
build-backend = "scikit_build_core.build"

[project]
name = "pytango"
version = "9.4.1"

[tool.scikit-build]
# This activates verbose builds
cmake.verbose = true

[tool.scikit-build.cmake.define]
# Put CMake defines in this table.
TANGO_ROOT="/Users/ulrik/soft/installed/tango.9.4"
